#pragma once

#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_BUILD_COUNT 0

#define STR1(x) #x
#define STR(x) STR1(x)

#define FILE_VERSION_STRING                                                                                            \
    STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH) "." STR(VERSION_BUILD_COUNT)
#define PRODUCT_VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH)

#define ROOMTUNES_VERSION_MAJOR VERSION_MAJOR
#define ROOMTUNES_VERSION_MINOR VERSION_MINOR
#define ROOMTUNES_VERSION_PATCH VERSION_PATCH
#define ROOMTUNES_VERSION_BUILD_COUNT VERSION_BUILD_COUNT
#define ROOMTUNES_FILE_VERSION_STRING FILE_VERSION_STRING
#define ROOMTUNES_PRODUCT_VERSION_STRING PRODUCT_VERSION_STRING
